### ISSUE TITLE
[BUG] Student Answers Quiz Questions

### ISSUE THREAD

**Issue by oliverrsebastian** [function-future/function-frontend#256]
**Describe the bug**
When a student in progress to answering all quiz questions, if the question is too long, i think it's better to have scrollable because i can't touch the buttons if i answers those in my mobile app

**To Reproduce**
1. Login as a student
1. Go to 'Grades'
2. Click on 'First Quiz'
2. Click on 'Start'
3. Find a question that is too long to describe

**Expected behavior**
Student can scroll and push buttons in that page

**Comment by DavidWilliamK** [comment]
Solved
