### ISSUE TITLE
[BUG] No link to score from quiz/assignment page

### ISSUE THREAD

**Issue by jonathan016** [function-future/function-frontend#274]
**Describe the bug**
After I finished a quiz/assignment and I revisit the quiz/assignment detail again, I cannot navigate to my score on that quiz/assignment *OR* view my score on that quiz/assignment. This is kind of frustrating as I had no clue to go to page `Points`.

**To Reproduce**
1. Login as student
2. Click on 'Tasks' menu
3. Click on any quiz/assignment detail
4. No link to previous score is given

**Expected behavior**
I expect to have a link to latest score on that quiz/assignment, or at least a link to 'Points' menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/33094792/74040863-25507100-49f7-11ea-8b73-e6369fd7513e.png)

**Please add these extra information:**
 - OS: Windows, Android
 - Browser: Chrome
 - Version: 79

**Comment by DavidWilliamK** [comment]
Expected, as there currently is no available way to obtain score for a specific quiz and/or assignment.
