### ISSUE TITLE
[BUG] Oval buttons on judging list

### ISSUE THREAD

**Issue by jonathan016** [function-future/function-frontend#277]
**Describe the bug**
Buttons on judging list have oval shape, whereas other buttons in the app have dull border but rectangular shape.

**To Reproduce**
1. Login as admin
2. Click on 'Judging' tab
3. See error

**Expected behavior**
The buttons should be rectangular with dull border.

**Screenshots**
![image](https://user-images.githubusercontent.com/33094792/74041466-46659180-49f8-11ea-9738-92d46a70ea4d.png)

**Please add these extra information:**
 - OS: Windows
 - Browser: Chrome
 - Version: 79

**Comment by DavidWilliamK** [comment]
Fixed on #266

**Comment by DavidWilliamK** [comment]
Merged
