### ISSUE TITLE
[BUG] Gap between students info in judging detail

### ISSUE THREAD

**Issue by jonathan016** [function-future/function-frontend#278]
**Describe the bug**
A gap between students info in judging detail page occurs whenever a student was added later than the compared student, which results in the former student having unequal assigned quiz/assignment to the latter student.

**To Reproduce**
1. Login as admin/mentor/judge
2. Click on 'Judging' tab
3. Click any judging detail
4. See error if the student is added in different time, with different quiz/assignment list

**Expected behavior**
Probably make both students stick to top. Other suggestions are open.

**Screenshots**
![image](https://user-images.githubusercontent.com/33094792/74041848-018e2a80-49f9-11ea-9ff4-13d1ce2ccebb.png)
![image](https://user-images.githubusercontent.com/33094792/74041865-094dcf00-49f9-11ea-833c-f2d459667ec6.png)

**Please add these extra information:**
 - OS: Windows
 - Browser: Chrome
 - Version: 79

**Comment by DavidWilliamK** [comment]
Fixed in #266

**Comment by DavidWilliamK** [comment]
Merged
